---
engines:
  brakeman:
    enabled: false
  rubocop:
    enabled: true
    channel: rubocop-0-51
    checks:
      Rubocop/Style/RaiseArgs:
        enabled: false
      Rubocop/Style/ConditionalAssignment:
        enabled: false
  bundler-audit:
    enabled: true
  reek:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - ruby
      - javascript
  fixme:
    enabled: true
  markdownlint:
    enabled: false
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.js"
  - "**.css"
  - Gemfile.lock
exclude_paths:
- config/**/*
- "coverage/**/*"
- db/**/*
- features/**/*
- "log/**/*"
- node_modules/**/*
- script/**/*
- spec/**/*
- test/**/*
- tmp/**/*
- vendor/**/*
- "**/spec"
