env:
  global:
    - CC_TEST_REPORTER_ID=2628b1e9df8282f3430f007bcd0ad98f3e29463078602afb9126901872d93b43
language: ruby
services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - echo "DATABASE_URL='postgres://localhost/travis_ci_test'" > .env.test
  - echo "SESSION_SECRET='8dab59a91eab93b3675f787cca843527'" >> .env.test
  - bundle exec rake db:migrate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
